linters:
  # Additionally enabled linters.
  enable:
    - dogsled
    - dupl
    - exhaustive
    - exportloopref
    - goconst
    - godot
    - gofumpt
    - goimports
    - gomnd
    - importas
    - revive
    - unconvert
    - unparam
    - whitespace
  fast: false
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  gomnd:
    settings:
      mnd:
        ignored-functions: strconv.FormatInt
  importas:
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
