version: "2"
linters:
  enable:
    - copyloopvar
    - dogsled
    - dupl
    - exhaustive
    - goconst
    - godot
    - importas
    - mnd
    - revive
    - unconvert
    - unparam
    - whitespace
  settings:
    exhaustive:
      default-signifies-exhaustive: true
    importas:
      alias:
        - pkg: k8s.io/api/core/v1
          alias: corev1
        - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
          alias: metav1
    mnd:
      ignored-functions:
        - '^flag\.'
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
                - github.com/onsi/ginkgo/v2
                - github.com/onsi/gomega
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/guacamole-operator/guacamole-operator
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
