linters:
  # Additionally enabled linters.
  enable:
    - dogsled
    - dupl
    - exhaustive
    - copyloopvar
    - goconst
    - godot
    - gofumpt
    - goimports
    - mnd
    - importas
    - revive
    - unconvert
    - unparam
    - whitespace
  fast: false
linters-settings:
  exhaustive:
    default-signifies-exhaustive: true
  importas:
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1
  revive:
    rules:
      - name: dot-imports
        arguments:
          - allowedPackages:
              - github.com/onsi/ginkgo/v2
              - github.com/onsi/gomega
