# permissions for end users to edit connections.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: connection-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: guacamole-operator
    app.kubernetes.io/part-of: guacamole-operator
    app.kubernetes.io/managed-by: kustomize
  name: connection-editor-role
rules:
- apiGroups:
  - guacamole-operator.github.io
  resources:
  - connections
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - guacamole-operator.github.io
  resources:
  - connections/status
  verbs:
  - get
