apiVersion: guacamole-operator.github.io/v1alpha1
kind: Connection
metadata:
  labels:
    app.kubernetes.io/name: connection
    app.kubernetes.io/instance: connection-sample
    app.kubernetes.io/part-of: guacamole-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: guacamole-operator
  name: connection-sample
spec:
  # TODO(user): Add fields here
