apiVersion: guacamole-operator.github.io/v1alpha1
kind: Guacamole
metadata:
  labels:
    app.kubernetes.io/name: guacamole
    app.kubernetes.io/instance: guacamole-sample
    app.kubernetes.io/part-of: guacamole-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: guacamole-operator
  name: guacamole-sample
spec:
  channel: dev
  auth:
    oidc:
      params:
        - name: OPENID_AUTHORIZATION_ENDPOINT
          valueFrom:
            name: guacamole-oidc
            key: authorization-endpoint
        - name: OPENID_JWKS_ENDPOINT
          valueFrom:
            name: guacamole-oidc
            key: jwks-endpoint
        - name: OPENID_ISSUER
          valueFrom:
            name: guacamole-oidc
            key: issuer
        - name: OPENID_CLIENT_ID
          valueFrom:
            name: guacamole-oidc
            key: clientID
        - name: OPENID_REDIRECT_URI
          valueFrom:
            name: guacamole-oidc
            key: redirect-uri
    postgres:
      params:
        - name: POSTGRESQL_HOSTNAME
          valueFrom:
            name: guacamoledb-pguser-guacamoledb
            key: host
        - name: POSTGRESQL_PORT
          valueFrom:
            name: guacamoledb-pguser-guacamoledb
            key: port
        - name: POSTGRESQL_DATABASE
          valueFrom:
            name: guacamoledb-pguser-guacamoledb
            key: dbname
        - name: POSTGRESQL_USER
          valueFrom:
            name: guacamoledb-pguser-guacamoledb
            key: user
        - name: POSTGRESQL_PASSWORD
          valueFrom:
            name: guacamoledb-pguser-guacamoledb
            key: password
  tls:
    caCertificates:
      secretRef:
        name: guacamole-ca-certs
  additionalSettings:
    extension-priority: "*, openid"
