apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - guacamole.yaml
  - guacd.yaml
  - sa.yaml

images:
  - name: docker.io/guacamole/guacd:latest
    newTag: 1.5.0
  - name: docker.io/guacamole/guacamole:latest
    newTag: 1.5.0
