apiVersion: v1
kind: ServiceAccount
metadata:
  name: guacamole
  labels:
    app.kubernetes.io/name: guacamole
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guacd
  labels:
    app.kubernetes.io/name: guacamole
