name: build

on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - go.mod
      - go.sum
      - Containerfile
      - config/**
      - channels/**.yaml
    tags:
      - v*
  workflow_dispatch:

env:
  OPERATOR_NAME: guacamole-operator
  OPERATOR_IMAGE_NAME: guacamole-operator
  OPERATOR_BUNDLE_IMAGE_NAME: guacamole-operator-bundle
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  test:
    name: Run go tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - run: make test

  version:
    name: Generate SemVer
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code with git history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate basic SemVer inputs
        id: semver
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          tag_prefix: v
          version_format: "${major}.${minor}.${patch}"

      - name: Generate final SemVer
        id: version
        run: |
          semver=${{ steps.semver.outputs.version }}
          timestamp=$(git log -1 --date=format:%Y%m%d%H%M%S --format=%cd)
          sha=$(git rev-parse --short HEAD)
          version=${semver}

          if [ "${{ startsWith(github.ref, 'refs/tags/v') }}" != "true" ]; then
            version=${semver}-${timestamp}-${sha}
          fi

          echo "version=${version}" >> $GITHUB_OUTPUT

  container:
    name: Build operator image
    runs-on: ubuntu-latest
    needs: [test, version]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        id: build
        with:
          image: ${{ env.OPERATOR_IMAGE_NAME }}
          tags: ${{ needs.version.outputs.version }}
          containerfiles: |
            ./Containerfile

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Print push output
        run: echo "${{ toJSON(steps.push.outputs) }}"

  bundle:
    name: Build operator bundle image
    runs-on: ubuntu-latest
    needs: [container, version]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download operator-sdk
        run: |
          export ARCH=$(case $(uname -m) in x86_64) echo -n amd64 ;; aarch64) echo -n arm64 ;; *) echo -n $(uname -m) ;; esac)
          export OS=$(uname | awk '{print tolower($0)}')
          export OPERATOR_SDK_DL_URL=https://github.com/operator-framework/operator-sdk/releases/download/v1.27.0
          curl -LO ${OPERATOR_SDK_DL_URL}/operator-sdk_${OS}_${ARCH}
          chmod +x operator-sdk_${OS}_${ARCH} && sudo mv operator-sdk_${OS}_${ARCH} /usr/local/bin/operator-sdk

      - name: Generate bundle
        run: |
          version=${{ needs.version.outputs.version }}
          image=${{ env.OPERATOR_IMAGE_NAME }}:${version}
          registry=${{ env.IMAGE_REGISTRY }}

          make bundle IMG=${registry}/${image} VERSION=${version}

      - name: Build bundle image
        uses: redhat-actions/buildah-build@v2
        id: build
        with:
          image: ${{ env.OPERATOR_BUNDLE_IMAGE_NAME }}
          tags: ${{ needs.version.outputs.version }}
          containerfiles: |
            ./bundle.Dockerfile

      - name: Push to GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Print push output
        run: echo "${{ toJSON(steps.push.outputs) }}"
