name: build

on:
  push:
    branches:
      - main
    paths:
      - containers/extension-dl/**
  pull_request:
    paths:
      - containers/extension-dl/**
  workflow_dispatch:

env:
  IMAGE_NAME: extension-dl
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
  REGISTRY_USER: ${{ github.actor }}
  REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate version
        id: version
        run: |
          sha=$(git rev-parse --short HEAD)
          version=${sha}

          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Build image
        uses: redhat-actions/buildah-build@v2
        id: build
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ steps.version.outputs.version }}
          context: ./containers/extension-dl
          containerfiles: |
            ./containers/extension-dl/Containerfile

      - name: Push to GHCR
        if: ${{ github.event_name == 'push' }}
        uses: redhat-actions/push-to-registry@v2
        id: push
        with:
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Print push output
        if: ${{ github.event_name == 'push' }}
        run: echo "${{ toJSON(steps.push.outputs) }}"
